name: go vet test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  statictest:
    runs-on: ubuntu-latest
    container: golang:1.24.4
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup autotest binary
        run: |
          git clone https://github.com/mipt-golang-course/go-autotests.git
          cd go-autotests
          go build -o $GITHUB_WORKSPACE/.tools/statictest ./cmd/statictest
          chmod -R +x $GITHUB_WORKSPACE/.tools/statictest
          mv $GITHUB_WORKSPACE/.tools/statictest /usr/local/bin/statictest

      - name: Run statictest
        run: |
          go vet -vettool=$(which statictest) ./...
